### PR TITLE
FTPizza#33-save-connection-info

### PR DESCRIPTION
**Pull request by SoySauceLabs**
# First Things First:
- [ ] Check it out!

### CODE REVIEW

**Comment by kevbui** [comment]
I think you should move all this into a separate file.

**Comment by kevbui** [comment]
PR looks good. The only problem is that if you corrupt the connection.txt, you get array out of bounds errors.  We can merge the PR anyways though

**Comment by SoySauceLabs** [comment]
Good call, I'm going to throw in a simple check for "corruption" (i.e. if it's missing data).

**Comment by kevbui** [comment]
The getter functions can be implemented in auto properities
There seems to be a problem when we create a login, the connection.txt is never written to

**Comment by SoySauceLabs** [comment]
Weird, what version of Visual Studio are you running? If definitely writing to file on my machine.

**Comment by kevbui** [comment]
When I delete the connection.txt and let the program create a fresh one. Then it gives me a outbounds error

**Comment by SoySauceLabs** [comment]
Good catch! Should be fixed now.

**Pull request merged**
